### PR TITLE
feat: thinking on how to reduce the redudancy with check declaration

### PR DESCRIPTION
**Pull request by kjappelbaum**
- [X] Breaking change (fix or feature that would cause existing functionality to change)

I'm still not sure what the best design is to reduce redundancy but still allow for easy access via good property names and efficiency (e.g., via caching).

The original motivation for the `check` dictionary was that one could loop over all checks and then get `is_ok`, a `name`, and a `description` and maybe a few more methods.  But in the current way we create the `checks` dictionary it leads to a call to the `graph` property and therefore to graph construction (#144). 
The other design goal was to *not* have an object, e.g a list, *outside* of the class which would need to be updated when we add a new check.

We could solve the latter with a metaclass approach, where we register some properties in a `descriptor` attribute in the class. 
It is still not clear to me how we make a good mapping to the descriptor. ATM, the most feasible approach to me seems to register the check classes also as properties of the mofchecker class which we decorate with something like `check`. This would populate a `checks` list. For the frontend, we could then loop over those checks and get name, description, check result, ....   
Latter should also allow us to add eqeq and zeo++ only to the check if a class variable is set accordingly

### CODE REVIEW

**Comment by ltalirz** [comment]
> The other design goal was to _not_ have an object, e.g a list, _outside_ of the class which would need to be updated when we add a new check.

I'm just wondering what the use case is that led to this requirement (e.g. dynamically changing the number of checks known to the MOFChecker class)?

If there is one, let me know and we can think about the easiest solution to address it.
If there isn't, perhaps you are overthinking things here a bit?

**Comment by ltalirz** [comment]
any thoughts on this?

**Comment by kjappelbaum** [comment]
>I'm just wondering what the use case is that led to this requirement 

The hope to arrive at some point at a code where others can easily contribute without having to edit multiple places just to add a new check.

**Comment by ltalirz** [comment]
> The hope to arrive at some point at a code where others can easily contribute without having to edit multiple places just to add a new check.

Is that desirable? As long as it's documented, I would say that adding a check + registering it in one place is perfectly acceptable.

Even if checks are discovered "automagically", you may still need some manual management, e.g. to control which groups of checks to run under which circumstances.
In general, my advice for a low barrier to contribution would be to keep the infrastructure simple and to extend the [contributing guidelines](https://github.com/kjappelbaum/mofchecker/blob/master/CONTRIBUTING.md).

P.S. I still think it's important to allow users to decide the checks that they want, i.e. creating the `MOFChecker` instance should be instantaneous and not create the graph etc.

**Pull request closed without merging**
